name: Build & Release Symbols

on:
  push:
    tags: ["symbols-*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y inkscape ffmpeg
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Build C01 & C02
        run: |
          python c01_pack/build_c01_symbol_pack.py
          python c02_pack/build_c02_symbol_pack.py

      - name: Generate CHECKSUMS
        run: |
          mkdir -p release/${{ github.ref_name }}
          sha256sum c01_pack/C01_symbol_extended_pack_v1.1.zip >  release/${{ github.ref_name }}/CHECKSUMS.txt
          sha256sum c02_pack/C02_symbol_pack_v1.0.zip       >> release/${{ github.ref_name }}/CHECKSUMS.txt

      - name: Export MP4 from GIF (C02)
        run: |
          find c02_pack/C02_symbol_pack_v1.0 -name "*.gif" -print0 | \
            xargs -0 -I{} ffmpeg -y -i "{}" -movflags +faststart -pix_fmt yuv420p \
              -vf "scale=800:-2:flags=lanczos,fps=24" "$(dirname "{}")/$(basename "{}" .gif).mp4"

      - name: Create/Upload Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF_NAME}"
          gh release view "$tag" || gh release create "$tag" --title "$tag" --notes "Auto-build"
          gh release upload "$tag" c01_pack/C01_symbol_extended_pack_v1.1.zip --clobber
          gh release upload "$tag" c02_pack/C02_symbol_pack_v1.0.zip       --clobber
          gh release upload "$tag" release/$tag/CHECKSUMS.txt               --clobber
          # MP4 (якщо є)
          mp4s=$(find c02_pack/C02_symbol_pack_v1.0 -name "*.mp4" -type f)
          if [ -n "$mp4s" ]; then gh release upload "$tag" $mp4s --clobber; fi
